### ISSUE TITLE
Vehicles spawning in the ground.

### ISSUE THREAD

**Issue by Mcguy65** [CryTheSly/Vehicle-Events#2]
Getting many reports from players that aircraft vehicles spawn gliched into the ground and blow up when a player tries to lift off.
I am using the map Russia.

**Comment by Mcguy65** [comment]
Also, vehicles spawn on top of eachother (if not taken) Anyway to fix this? thanks!

**Comment by CryTheSly** [comment]
Just enable despawning. Should fix the issue.
